apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  selector:
    app:spring-boot-app
  ports:
    - protocol: TCP
      port: 80            # Port exposed inside the cluster
      targetPort: 8080    # Port your container listens on
  type: NodePort      # Change to ClusterIP or NodePort as needed
